// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var FormData$Phantomtyperescript = require("./FormData.bs.js");

console.log("Hello, BuckleScript and Rescript!");

var a = FormData$Phantomtyperescript.formData("foobar");

var b = FormData$Phantomtyperescript.validate(a);

var c = FormData$Phantomtyperescript.upperCase(FormData$Phantomtyperescript.formData("foobar"));

console.log("formData(unvalidated): ", a);

console.log("option(formData(validated)): ", b);

console.log("upperCase foobar: ", c);

var a$1 = FormData$Phantomtyperescript.formData("foobar");

var b$1 = FormData$Phantomtyperescript.validate(a$1);

exports.c = c;
exports.a = a$1;
exports.b = b$1;
/*  Not a pure module */
